# Generated by Django 5.2.13 on 2026-08-25 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('megapixels', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('software', models.CharField(blank=True, max_length=200)),
                ('date_original', models.CharField(blank=True, max_length=100)),
                ('modify_date', models.CharField(blank=True, max_length=100)),
                ('exposure_time', models.CharField(blank=True, max_length=50)),
                ('f_number', models.FloatField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('resolution_width', models.IntegerField(blank=True, null=True)),
                ('resolution_height', models.IntegerField(blank=True, null=True)),
                ('c2pa_present', models.BooleanField(default=False)),
                ('exif_full', models.JSONField(blank=True, null=True)),
                ('ai_tool', models.CharField(blank=True, max_length=100)),
                ('verdict', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_analysis', to='authenticate.uploadedimage')),
            ],
        ),
        migrations.CreateModel(
            name='HumanEditDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap', models.ImageField(upload_to='outputs/')),
                ('overlay', models.ImageField(upload_to='outputs/')),
                ('detection_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_name', models.CharField(default='TruFor', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('heatmap_analyzed', models.BooleanField(default=False)),
                ('heatmap_last_accessed', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_edit_detection', to='authenticate.uploadedimage')),
            ],
        ),
        migrations.CreateModel(
            name='FinalVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_verdict', to='authenticate.uploadedimage')),
            ],
        ),
        migrations.CreateModel(
            name='AIDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('model_name', models.CharField(default='ResNet50', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_detection', to='authenticate.uploadedimage')),
            ],
        ),
        migrations.CreateModel(
            name='QnAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('question_type', models.CharField(choices=[('LOCATION', 'Where edited'), ('REASON', 'Why AI/edited'), ('CONFIDENCE', 'How confident'), ('SEVERITY', 'How severe'), ('GENERAL', 'General question'), ('COMPARISON', 'Compare regions')], default='GENERAL', max_length=50)),
                ('used_ai_confidence', models.FloatField(blank=True, null=True)),
                ('used_human_score', models.FloatField(blank=True, null=True)),
                ('used_primary_region', models.CharField(blank=True, max_length=50)),
                ('used_verdict', models.CharField(blank=True, max_length=100)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('was_from_cache', models.BooleanField(default=False)),
                ('helpful_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_history', to='authenticate.uploadedimage')),
            ],
            options={
                'ordering': ['-asked_at'],
                'indexes': [models.Index(fields=['image', '-asked_at'], name='authenticat_image_i_eb05c3_idx'), models.Index(fields=['image', 'question_type'], name='authenticat_image_i_01e204_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeatmapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_scores', models.JSONField(blank=True, null=True)),
                ('max_edit_score', models.FloatField(default=0.0)),
                ('avg_edit_score', models.FloatField(default=0.0)),
                ('edited_percentage', models.FloatField(default=0.0)),
                ('primary_region', models.CharField(blank=True, max_length=50)),
                ('secondary_region', models.CharField(blank=True, max_length=50)),
                ('region_scores', models.JSONField(blank=True, null=True)),
                ('edit_zones_count', models.IntegerField(default=0)),
                ('zones_details', models.JSONField(blank=True, null=True)),
                ('severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='LOW', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_analysis', to='authenticate.uploadedimage')),
            ],
            options={
                'indexes': [models.Index(fields=['image', '-analyzed_at'], name='authenticat_image_i_65c2b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('include_heatmap', models.BooleanField(default=False)),
                ('include_images', models.BooleanField(default=True)),
                ('verdict_snapshot', models.CharField(blank=True, max_length=100)),
                ('ai_score_snapshot', models.FloatField(blank=True, null=True)),
                ('human_score_snapshot', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='authenticate.uploadedimage')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['image', '-generated_at'], name='authenticat_image_i_7cce07_idx'), models.Index(fields=['generated_by', '-generated_at'], name='authenticat_generat_75addf_idx')],
            },
        ),
    ]
