# utils/qa_system.py
import re
from .models import UploadedImage, AIDetection, HumanEditDetection, HeatmapAnalysis, FinalVerdict, QnAHistory, MetadataAnalysis

class ImageQASystem:
    """Complete Q&A system - answers ANY question from database results"""
    
    def __init__(self):
        pass
    
    def _detect_intent(self, question):
        """Detect intent from ANY possible question - priority order matters"""
        q = question.lower().strip()
        
        # ============================================================
        # AI MODEL QUESTIONS (HIGHEST PRIORITY)
        # ============================================================
        
        ai_model_patterns = [
            r'\b(what model|which model|what ai|which ai|ai model|model name)\b',
            r'\b(made by|generated by|created by|produced by)\s+(what|which|what ai|which ai)\b',
            r'\b(what generated|what created|what made)\s+this\b',
            r'\b(model (used|that made|that generated))\b',
            r'\b(what tool|which tool|generated with what)\b',
            r'\b(ai name|ai type|generator|generation tool)\b',
        ]
        if any(re.search(p, q) for p in ai_model_patterns):
            return 'AI_MODEL'
        
        # ============================================================
        # AI DETECTION QUESTIONS (HIGH PRIORITY - BEFORE DATE)
        # ============================================================
        
        # Is it AI? - Check for "AI generated" specifically
        if re.search(r'\b(is this (ai|fake|synthetic)|this ai\?|ai or not|real or ai|is it ai)\b', q):
            return 'WHY_AI'
        
        if re.search(r'\b(ai generated|ai-generated|generated by ai)\b', q):
            return 'WHY_AI'
        
        # What percentage AI?
        if re.search(r'\b(what percentage|how much percent|ai probability|ai chance|likelihood ai)\b', q):
            return 'CONFIDENCE'
        
        # Is it real/authentic?
        real_patterns = [
            r'\b(is this real|this real\?|is it real|real or fake|authentic or not)\b',
            r'\b(can i trust|should i trust|is it trustworthy|is it genuine|is it legitimate)\b',
            r'\b(is it authentic|this authentic|original or fake)\b',
        ]
        if any(re.search(p, q) for p in real_patterns):
            return 'TRUST'
        
        # ============================================================
        # METADATA INTENTS
        # ============================================================
        
        # Camera/Device
        camera_patterns = [
            r'\b(camera|device|make|model|phone|smartphone|brand|manufacturer)\b',
            r'\b(what camera|which camera|what phone|what device)\b',
            r'\b(taken with|shot with|captured with|photo with)\b',
        ]
        if any(re.search(p, q) for p in camera_patterns):
            if not re.search(r'\b(ai|generated)\b', q):
                return 'METADATA_CAMERA'
        
        # Software/Editor
        software_patterns = [
            r'\b(software|editor|tool|app|application|program)\b',
            r'\b(photoshop|lightroom|gimp|edited with|created with)\b',
            r'\b(what software|which software|what editor)\b',
        ]
        if any(re.search(p, q) for p in software_patterns):
            return 'METADATA_SOFTWARE'
        
        # Date/Time - but NOT if it's asking about AI generation
        if not re.search(r'\b(ai generated|ai-generated|generated by ai|is this ai)\b', q):
            date_patterns = [
                r'\b(date|when|time|timestamp|taken|captured|shot|created|generated|modified|uploaded)\b',
                r'\b(what date|what time|what year|when was)\b',
            ]
            if any(re.search(p, q) for p in date_patterns):
                return 'METADATA_DATE'
        
        # GPS/Location
        if re.search(r'\b(gps|coordinates|latitude|longitude|where (was|is) it (taken|captured|shot))\b', q):
            return 'METADATA_GPS'
        
        # Camera Settings
        settings_patterns = [
            r'\b(settings|exif|exposure|shutter speed|aperture|f-stop|iso|focal length|resolution|dimension)\b',
            r'\b(camera settings|exif data)\b',
        ]
        if any(re.search(p, q) for p in settings_patterns):
            return 'METADATA_SETTINGS'
        
        # AI Tool Detection
        aitool_patterns = [
            r'\b(ai tool|generation tool|tool used)\b',
            r'\b(midjourney|dalle|stable diffusion|chatgpt|firefly|bing image|leonardo|playground|copilot|gemini|claude)\b',
            r'\b(what tool|which tool|generated with what|what generated this)\b',
        ]
        if any(re.search(p, q) for p in aitool_patterns):
            return 'METADATA_AITOOL'
        
        # C2PA/Integrity
        if re.search(r'\b(c2pa|integrity|signed|certificate|authenticity|tampered|original|provenance|content credentials)\b', q):
            return 'METADATA_INTEGRITY'
        
        # General metadata
        if re.search(r'\b(metadata|exif|file info|image info|details|information about|tell me about)\b', q):
            return 'METADATA_GENERAL'
        
        # ============================================================
        # IMAGE ANALYSIS INTENTS
        # ============================================================
        
        # Where is it edited?
        if re.search(r'\bwhere\s+(is|was|exactly)\s+(it\s+)?(edited|manipulat|modified|changed|altered)\b', q):
            return 'WHERE'
        
        if q in ['where?', 'where exactly?', 'which part?', 'location?', 'what area?', 'show me where', 'edit location?']:
            return 'WHERE'
        
        # How is it edited?
        if re.search(r'\bhow\s+(is|was|did)\s+(it\s+)?(edited|manipulat|modified|changed)\b', q):
            return 'HOW_EDITED'
        
        # Combined how and where
        if re.search(r'\bhow.*and where|where.*and how\b', q):
            return 'HOW_AND_WHERE'
        
        # General editing detection
        if re.search(r'\b(edited|manipulated|modified|altered|tampered|photoshopped|retouched)\b', q):
            if 'where' not in q and 'how' not in q:
                return 'WHY_EDITED'
        
        # What was edited?
        if re.search(r'\bwhat.*(edited|changed|modified|manipulated|done|altered)\b', q):
            return 'WHAT_EDITED'
        
        # How much was edited?
        if re.search(r'\b(how much|percentage|percent|portion|amount|area)\s+edited\b', q):
            return 'HOW_MUCH'
        
        # Confidence
        if re.search(r'\b(confident|confidence|sure|certain|how sure|how confident|reliable|accurate|trust score|probability)\b', q):
            return 'CONFIDENCE'
        
        # Severity
        if re.search(r'\b(severe|severity|bad|heavily|intense|serious|how bad|how severe|degree|extent|level)\b', q):
            return 'SEVERITY'
        
        # Verdict
        if re.search(r'\b(verdict|result|conclusion|decision|finding|what.*say|overall|final result|what is the verdict)\b', q):
            return 'VERDICT'
        
        # Comparison
        if re.search(r'\b(compare|comparison|difference|versus|vs|between|contrast)\b', q):
            return 'COMPARE'
        
        # Explanation
        if re.search(r'\b(explain|describe|elaborate|clarify|tell me about|what does this mean|how does this work)\b', q):
            return 'EXPLANATION'
        
        # ============================================================
        # FILE & UPLOAD INFO
        # ============================================================
        
        if re.search(r'\b(filename|file name|file size|size|format|type|dimensions|resolution|megapixel)\b', q):
            return 'FILE_INFO'
        
        if re.search(r'\b(uploaded by|who uploaded|owner|creator|author|who submitted|uploader)\b', q):
            return 'UPLOAD_INFO'
        
        # ============================================================
        # HEATMAP & SCORES
        # ============================================================
        
        if re.search(r'\b(heatmap|heat map|hotspot|hot spot|red area|red zone|color map|manipulation map)\b', q):
            return 'HEATMAP'
        
        if re.search(r'\b(score|rating|value|metric|edit score|manipulation score|detection score|confidence score)\b', q):
            return 'SCORES'
        
        # ============================================================
        # RECOMMENDATIONS
        # ============================================================
        
        if re.search(r'\b(recommend|suggest|advice|opinion|what should i|should i use|use this|can i use|is it safe)\b', q):
            return 'RECOMMEND'
        
        # ============================================================
        # GENERAL KNOWLEDGE QUESTIONS
        # ============================================================
        
        if re.search(r'\b(what is|what are|define|meaning of|explain)\s+(c2pa|exif|metadata|heatmap)\b', q):
            return 'EXPLANATION'
        
        # ============================================================
        # PERSONAL & GREETINGS
        # ============================================================
        
        greetings = ['hello', 'hi', 'hey', 'greetings', 'good morning', 'good afternoon', 'good evening', 'howdy', 'sup', 'yo']
        if q.strip() in greetings:
            return 'GREETING'
        
        personal_patterns = [
            r'\b(i love|love you|you are (great|awesome|amazing|smart|intelligent))\b',
            r'\b(how are you|how do you do|how\'s it going)\b',
            r'\b(what is your name|who are you|your name|who made you)\b',
            r'\b(thank you|thanks|appreciate|good job)\b',
            r'\b(sorry|my fault|i apologize)\b',
            r'\b(what can you do|help me|capabilities|features)\b',
            r'\b(are you (human|person|real|alive|conscious))\b',
            r'\b(tell me a joke|make me laugh|say something funny)\b',
        ]
        if any(re.search(p, q) for p in personal_patterns):
            return 'PERSONAL'
        
        # ============================================================
        # INVALID & NONSENSE
        # ============================================================
        
        if len(q) < 4:
            return 'INVALID'
        
        common_names = ['alex', 'john', 'mary', 'peter', 'paul', 'james', 'robert', 'michael', 'david', 'william', 'sarah', 'lisa', 'jennifer', 'mwakenja', 'elvis', 'obama', 'trump', 'biden']
        if any(name in q for name in common_names):
            if not any(word in q for word in ['image', 'photo', 'picture', 'edit', 'ai', 'detect']):
                return 'NONSENSE'
        
        # ============================================================
        # DEFAULT
        # ============================================================
        
        if any(word in q for word in ['image', 'photo', 'picture', 'this', 'picture']):
            return 'GENERAL'
        
        return 'OFF_TOPIC'
    
    def get_image_analysis_data(self, image_id):
        """Fetch ALL analysis results from database"""
        try:
            image = UploadedImage.objects.get(id=image_id)
            ai = AIDetection.objects.filter(image=image).first()
            human = HumanEditDetection.objects.filter(image=image).first()
            heatmap = HeatmapAnalysis.objects.filter(image=image).first()
            verdict = FinalVerdict.objects.filter(image=image).first()
            metadata = MetadataAnalysis.objects.filter(image=image).first()
            
            missing = []
            if not ai: missing.append("AI detection")
            if not human: missing.append("human edit detection")
            if not heatmap: missing.append("heatmap analysis")
            if not verdict: missing.append("final verdict")
            
            if missing:
                return None, f"Analysis incomplete. Missing: {', '.join(missing)}. Run analysis first."
            
            # Parse metadata verdict for AI tool info
            metadata_verdict = metadata.verdict if metadata else ""
            ai_tool_from_verdict = ""
            
            if metadata_verdict:
                # First check for common AI tool names
                ai_tools = ['midjourney', 'dalle', 'stable diffusion', 'chatgpt', 'firefly', 
                           'leonardo', 'playground', 'bing', 'copilot', 'gemini', 'claude', 
                           'imagen', 'craiyon', 'wombo', 'nightcafe', 'starryai']
                for tool in ai_tools:
                    if tool in metadata_verdict.lower():
                        ai_tool_from_verdict = tool.title()
                        break
                
                # If not found, try regex patterns
                if not ai_tool_from_verdict:
                    ai_tool_patterns = [
                        r'AI-generated using ([^)]+)',
                        r'generated with ([^)]+)',
                        r'created by ([^)]+)',
                        r'using ([^)]+)',
                        r'midjourney|dalle|stable diffusion|chatgpt|firefly|leonardo|playground|bing',
                    ]
                    for pattern in ai_tool_patterns:
                        match = re.search(pattern, metadata_verdict.lower())
                        if match:
                            if '|' in pattern:
                                ai_tool_from_verdict = match.group(0).title() if match.group(0) else pattern.split('|')[0].title()
                            else:
                                ai_tool_from_verdict = match.group(1).strip().title() if match.groups() else match.group(0).title()
                            break
            
            return {
                'image': image,
                'ai': {'label': ai.label, 'confidence': ai.confidence},
                'human_edit': {'score': human.detection_score, 'is_edited': human.detection_score > 0.35},
                'heatmap': {
                    'primary': heatmap.primary_region,
                    'secondary': heatmap.secondary_region,
                    'max_score': heatmap.max_edit_score,
                    'avg_score': heatmap.avg_edit_score,
                    'edited_percent': heatmap.edited_percentage,
                    'severity': heatmap.severity_level,
                    'zones': heatmap.edit_zones_count,
                },
                'verdict': verdict.verdict,
                'overall_confidence': verdict.confidence_score if verdict else 0,
                'metadata': {
                    'camera_make': metadata.camera_make,
                    'camera_model': metadata.camera_model,
                    'software': metadata.software,
                    'date_original': metadata.date_original,
                    'modify_date': metadata.modify_date,
                    'gps_lat': metadata.gps_latitude,
                    'gps_lon': metadata.gps_longitude,
                    'exposure': metadata.exposure_time,
                    'f_number': metadata.f_number,
                    'iso': metadata.iso,
                    'focal_length': metadata.focal_length,
                    'width': metadata.resolution_width,
                    'height': metadata.resolution_height,
                    'c2pa': metadata.c2pa_present,
                    'ai_tool': metadata.ai_tool or ai_tool_from_verdict,
                    'verdict_text': metadata.verdict,
                }
            }, None
        except Exception as e:
            return None, f"Error: {str(e)}"
    
    def get_answer(self, image_id, question):
        """Main entry - answers 80+ question types"""
        
        intent = self._detect_intent(question)
        
        # Handle personal/greeting first
        if intent == 'GREETING':
            return self._greeting(), False
        if intent == 'PERSONAL':
            return self._personal_response(question), False
        if intent == 'INVALID':
            return self._invalid(), False
        if intent == 'NONSENSE':
            return self._nonsense(), False
        
        # Get analysis data
        data, error = self.get_image_analysis_data(image_id)
        if error:
            return error, False
        
        # Check cache
        cached = QnAHistory.objects.filter(image_id=image_id, question__iexact=question).first()
        if cached:
            return cached.answer, True
        
        # Route to appropriate handler
        handlers = {
            'AI_MODEL': self._ai_model,
            'METADATA_CAMERA': self._camera,
            'METADATA_SOFTWARE': self._software,
            'METADATA_DATE': self._date,
            'METADATA_GPS': self._gps,
            'METADATA_SETTINGS': self._settings,
            'METADATA_AITOOL': self._aitool,
            'METADATA_INTEGRITY': self._integrity,
            'METADATA_GENERAL': self._metadata_general,
            'WHY_AI': self._is_ai,
            'TRUST': self._trust,
            'WHY_EDITED': self._edited,
            'WHERE': self._where,
            'HOW_EDITED': self._how_edited,
            'HOW_AND_WHERE': self._how_and_where,
            'WHAT_EDITED': self._what_edited,
            'HOW_MUCH': self._how_much,
            'CONFIDENCE': self._confidence,
            'SEVERITY': self._severity,
            'VERDICT': self._verdict,
            'COMPARE': self._compare,
            'EXPLANATION': self._explanation,
            'FILE_INFO': self._file_info,
            'UPLOAD_INFO': self._upload_info,
            'HEATMAP': self._heatmap_info,
            'SCORES': self._scores,
            'RECOMMEND': self._recommend,
            'GENERAL': self._general,
            'OFF_TOPIC': self._off_topic,
        }
        
        handler = handlers.get(intent, self._general)
        answer = handler(data, question)
        
        # Save to cache
        QnAHistory.objects.create(
            image_id=image_id, question=question, answer=answer,
            question_type=intent, used_ai_confidence=data['ai']['confidence'],
            used_human_score=data['human_edit']['score'],
            used_primary_region=data['heatmap']['primary'],
            used_verdict=data['verdict'], was_from_cache=False
        )
        
        return answer, False
    
    # ============================================================
    # HELPER METHODS
    # ============================================================
    
    def _region_name(self, region):
        m = {
            'top_left': 'top-left corner', 'top_center': 'top-center area', 'top_right': 'top-right corner',
            'middle_left': 'left side', 'middle_center': 'center of the image', 'middle_right': 'right side',
            'bottom_left': 'bottom-left corner', 'bottom_center': 'bottom-center area', 'bottom_right': 'bottom-right corner',
            '': 'unknown area', None: 'unknown area'
        }
        if not region:
            return 'various areas'
        return m.get(region, region.replace('_', ' '))
    
    # ============================================================
    # PERSONAL RESPONSES
    # ============================================================
    
    def _greeting(self):
        return "Hello! I'm your image forensic assistant. Ask me about this image - is it AI-generated? Where was it edited? What camera was used? Or should you trust it?"
    
    def _personal_response(self, question):
        q = question.lower()
        if 'love' in q:
            return "That's kind! But let's focus on analyzing this image. What would you like to know about it?"
        if 'how are you' in q:
            return "I'm ready to analyze! Ask me anything about this image's authenticity, editing, or metadata."
        if 'name' in q or 'who are you' in q:
            return "I'm Forensix AI - your image forensic analyst. I can tell you if an image is real, AI-generated, edited, and more!"
        if 'thank' in q:
            return "You're welcome! Any other questions about this image?"
        if 'joke' in q:
            return "Why did the AI cross the road? To analyze the image on the other side! 😊 Now, about this image..."
        if 'help' in q or 'capabilities' in q:
            return "I can answer questions about: AI generation, editing locations, camera metadata, trustworthiness, heatmaps, and more! Just ask about this image."
        return "I'm here to help you analyze this image. Ask me about its authenticity, editing locations, camera details, or trustworthiness."
    
    def _invalid(self):
        return "Please ask a complete question. Examples: 'Is this AI generated?', 'Where was it edited?', 'What camera was used?'"
    
    def _nonsense(self):
        return "I only answer questions about this image's analysis. Ask about AI detection, editing locations, metadata, or authenticity."
    
    def _off_topic(self, data, q=None):
        return "I can only answer questions about this image's analysis. Try: 'Is this AI generated?', 'Where was it edited?', or 'Should I trust this image?'"
    
    # ============================================================
    # AI MODEL ANSWER (SHOWS AI TOOL NAME)
    # ============================================================
    
    def _ai_model(self, data, q=None):
        ai = data['ai']
        metadata = data['metadata']
        
        # Get AI tool/model name
        ai_tool = metadata.get('ai_tool', '')
        
        if ai_tool:
            if ai['label'] == 'AI-generated':
                return f"This image was generated with {ai_tool}. AI detection confidence: {ai['confidence']:.1f}%."
            else:
                return f"No AI model was used - this is a real image. Confidence: {ai['confidence']:.1f}%."
        
        if metadata.get('verdict_text') and 'AI-generated' in metadata['verdict_text']:
            verdict = metadata['verdict_text']
            if 'using' in verdict:
                tool = verdict.split('using')[-1].strip()
                return f"C2PA signatures indicate generation with {tool}. Confidence: {ai['confidence']:.1f}%."
        
        if ai['label'] == 'AI-generated':
            return f"This is AI-generated, but no specific model was identified. Confidence: {ai['confidence']:.1f}%."
        
        return f"This is NOT AI-generated. It's a real image with {ai['confidence']:.1f}% confidence."
    
    # ============================================================
    # METADATA ANSWERS
    # ============================================================
    
    def _camera(self, data, q=None):
        m = data['metadata']
        if m['camera_make'] or m['camera_model']:
            return f"This photo was taken with a {m['camera_make']} {m['camera_model']} camera."
        if data['ai']['label'] == 'AI-generated':
            return "No camera information - this is AI-generated content."
        return "No camera information found. This often happens with screenshots or social media uploads."
    
    def _software(self, data, q=None):
        m = data['metadata']
        if m['software']:
            return f"This image was edited using {m['software']}."
        return "No editing software detected in metadata."
    
    def _date(self, data, q=None):
        m = data['metadata']
        if m['date_original']:
            if m['date_original'] != m['modify_date']:
                return f"This photo was taken on {m['date_original']} and Last modified on {m['modify_date']}"
            else:
                return f"This photo was taken on {m['date_original']}"
        if m['modify_date']:
            return f"Last modified on {m['modify_date']}."
        return f"Uploaded on {data['image'].uploaded_at.strftime('%Y-%m-%d at %H:%M')} but captured date may be striped."
    
    def _gps(self, data, q=None):
        m = data['metadata']
        if m['gps_lat'] and m['gps_lon']:
            return f"GPS coordinates: {m['gps_lat']}, {m['gps_lon']}."
        return "No GPS location data found."
    
    def _settings(self, data, q=None):
        m = data['metadata']
        s = []
        if m['exposure']: s.append(f"{m['exposure']}s exposure")
        if m['f_number']: s.append(f"f/{m['f_number']}")
        if m['iso']: s.append(f"ISO {m['iso']}")
        if m['focal_length']: s.append(f"{m['focal_length']}mm")
        if m['width'] and m['height']: s.append(f"{m['width']}x{m['height']}")
        if s:
            return f"Camera settings: {', '.join(s)}."
        return "No detailed camera settings found."
    
    def _aitool(self, data, q=None):
        m = data['metadata']
        ai = data['ai']
        
        ai_tool = m.get('ai_tool', '')
        
        if ai_tool:
            return f"This image was generated with {ai_tool}."
        if m.get('verdict_text') and 'AI-generated' in m['verdict_text']:
            return f"C2PA signatures indicate AI generation. {m['verdict_text'][:100]}"
        if ai['label'] == 'AI-generated':
            return "This is AI-generated, but no specific tool was identified."
        return "No AI generation tool detected - this appears to be a real image."
    
    def _integrity(self, data, q=None):
        m = data['metadata']
        if m['c2pa']:
            return "✅ This image has C2PA cryptographic signatures - verifiable provenance and authenticity tracking."
        return "❌ No C2PA integrity signatures found. This image lacks cryptographic provenance verification."
    
    def _metadata_general(self, data, q=None):
        m = data['metadata']
        lines = ["📷 METADATA SUMMARY:"]
        if m['camera_make']:
            lines.append(f"• Camera: {m['camera_make']} {m['camera_model']}")
        else:
            lines.append("• Camera: Not detected")
        if m['software']:
            lines.append(f"• Software: {m['software']}")
        if m['date_original']:
            lines.append(f"• Date captured: {m['date_original']}")
        if m['ai_tool']:
            lines.append(f"• AI Tool: {m['ai_tool']}")
        lines.append(f"• C2PA Signed: {'✅ Yes' if m['c2pa'] else '❌ No'}")
        return '\n'.join(lines)
    
    # ============================================================
    # IMAGE ANALYSIS ANSWERS (USING OVERALL CONFIDENCE)
    # ============================================================
    
    def _is_ai(self, data, q=None):
        ai = data['ai']
        m = data['metadata']
        overall_conf = data.get('overall_confidence', 0)
        
        # Get AI tool name if available
        ai_tool = m.get('ai_tool', '')
        
        if ai['label'] == 'AI-generated':
            if ai_tool:
                if m['c2pa']:
                    return f"Yes, this is AI-generated using {ai_tool} (confirmed by C2PA signatures). {overall_conf:.1f}% confidence."
                return f"Yes, this is AI-generated using {ai_tool}. {overall_conf:.1f}% confidence."
            elif m['c2pa']:
                return f"Yes, this is AI-generated (confirmed by C2PA signatures). {overall_conf:.1f}% confidence."
            else:
                return f"Yes, this is AI-generated. {overall_conf:.1f}% confidence."
        
        return f"No, this is NOT AI-generated. It's a real image with {overall_conf:.1f}% confidence."
    
    def _trust(self, data, q=None):
        v = data['verdict']
        m = data['metadata']
        overall_conf = data.get('overall_confidence', 0)
        
        ai_tool = m.get('ai_tool', '')
        
        if v == "AUTHENTIC IMAGE":
            if m['c2pa']:
                return f"✅ Yes, you can trust this image. C2PA confirms authenticity. {overall_conf:.1f}% confidence."
            return f"✅ Yes, you can trust this image. {overall_conf:.1f}% confidence - authentic."
        if "AI Generated" in v:
            if ai_tool:
                return f"⚠️ No, do not trust this image. It's AI-generated using {ai_tool}. {overall_conf:.1f}% confidence."
            return f"⚠️ No, don't trust this image. It's {v.lower()}."
        if "Human Edited" in v:
            return f"⚠️ Use caution. This image is human-edited. Authenticity confidence: {overall_conf:.1f}%."
        return f"❓ Uncertain. {overall_conf:.1f}% confidence."
    
    def _edited(self, data, q=None):
        h = data['human_edit']
        if h['is_edited']:
            return f"Yes, human editing detected. Score: {h['score']:.2f} (threshold is 0.35)."
        return f"No significant human editing detected. Score: {h['score']:.2f} (below 0.35 threshold)."
    
    def _where(self, data, q=None):
        h = data['human_edit']
        hm = data['heatmap']
        if not h['is_edited']:
            return "No significant editing detected anywhere in this image."
        primary = self._region_name(hm['primary'])
        answer = f"Editing is concentrated in the {primary}"
        if hm['secondary']:
            answer += f", with additional editing in the {self._region_name(hm['secondary'])}"
        answer += f". Maximum edit score: {hm['max_score']:.2f}."
        if hm['zones'] > 1:
            answer += f" Detected {hm['zones']} distinct manipulation zones."
        return answer
    
    def _how_edited(self, data, q=None):
        h = data['human_edit']
        hm = data['heatmap']
        if not h['is_edited']:
            return "The image wasn't edited significantly - it appears natural with minimal alterations."
        intensity = "very heavily" if hm['max_score'] > 0.7 else "significantly" if hm['max_score'] > 0.5 else "moderately"
        region = self._region_name(hm['primary'])
        return f"The image was {intensity} edited in the {region} region. Manipulation score: {hm['max_score']:.2f}. About {hm['edited_percent']:.1f}% of the image area shows changes."
    
    def _how_and_where(self, data, q=None):
        h = data['human_edit']
        hm = data['heatmap']
        if not h['is_edited']:
            return "No significant editing detected anywhere in the image."
        intensity = "heavily" if hm['max_score'] > 0.7 else "significantly" if hm['max_score'] > 0.5 else "moderately"
        region = self._region_name(hm['primary'])
        return f"The image was {intensity} edited in the {region}. Editing score: {hm['max_score']:.2f}. Affected area: {hm['edited_percent']:.1f}% of the image."
    
    def _what_edited(self, data, q=None):
        h = data['human_edit']
        hm = data['heatmap']
        if not h['is_edited']:
            return "No significant edits were detected in this image."
        region = self._region_name(hm['primary'])
        return f"The {region} area was edited. Manipulation intensity score: {hm['max_score']:.2f}."
    
    def _how_much(self, data, q=None):
        hm = data['heatmap']
        h = data['human_edit']
        if not h['is_edited']:
            return f"Only {hm['edited_percent']:.1f}% of the image shows any detectable changes - very minimal."
        return f"Approximately {hm['edited_percent']:.1f}% of the image area shows signs of manipulation. Average edit score: {hm['avg_score']:.2f}."
    
    def _confidence(self, data, q=None):
        h = data['human_edit']
        overall_conf = data.get('overall_confidence', 0)
        if data['verdict'] == "AUTHENTIC IMAGE":
            base = f"I'm {overall_conf:.1f}% confident this image is authentic/real."
        elif "AI Generated" in data['verdict']:
            base = f"I'm {overall_conf:.1f}% confident this image is AI-generated."
        elif "Human Edited" in data['verdict']:
            base = f"I'm {overall_conf:.1f}% confident this image has been human-edited."
        else:
            base = f"I'm {overall_conf:.1f}% confident in this verdict."
        if h['is_edited']:
            base += f" Additionally, human editing detected with {h['score']:.2f} confidence."
        return base
    
    def _severity(self, data, q=None):
        hm = data['heatmap']
        severity_map = {
            'VERY_HIGH': 'very severe - extensive manipulation detected throughout', 
            'HIGH': 'severe - significant modifications present', 
            'MEDIUM': 'moderate - noticeable but limited changes', 
            'LOW': 'mild - only minor or subtle edits detected'
        }
        sev = severity_map.get(hm['severity'], hm['severity'].lower())
        return f"Editing severity: {sev}. Average edit score: {hm['avg_score']:.2f}. {hm['edited_percent']:.1f}% of the image affected."
    
    def _verdict(self, data, q=None):
        overall_conf = data.get('overall_confidence', 0)
        return f"Final verdict: {data['verdict']} (Overall confidence: {overall_conf:.1f}%)"
    
    def _compare(self, data, q=None):
        ai = data['ai']
        h = data['human_edit']
        hm = data['heatmap']
        overall_conf = data.get('overall_confidence', 0)
        return f"📊 COMPARISON:\n• AI Detection: {ai['label']} with {ai['confidence']:.1f}% confidence\n• Overall Confidence: {overall_conf:.1f}%\n• Human Editing: {'Detected' if h['is_edited'] else 'Not detected'} (score: {h['score']:.2f})\n• Primary Edit Location: {self._region_name(hm['primary'])}\n• Final Verdict: {data['verdict']}"
    
    def _explanation(self, data, q=None):
        ai = data['ai']
        h = data['human_edit']
        hm = data['heatmap']
        m = data['metadata']
        overall_conf = data.get('overall_confidence', 0)
        
        ai_tool = m.get('ai_tool', '')
        
        lines = [
            f"📊 FORENSIC ANALYSIS REPORT:",
            f"",
            f"• FINAL VERDICT: {data['verdict']}",
            f"• OVERALL CONFIDENCE: {overall_conf:.1f}%",
            f"• AI DETECTION: {ai['label']} with {ai['confidence']:.1f}% confidence",
        ]
        
        if ai_tool:
            lines.append(f"• AI TOOL IDENTIFIED: {ai_tool}")
        
        if h['is_edited']:
            lines.append(f"• HUMAN EDITING: Detected (score: {h['score']:.2f})")
            lines.append(f"• EDIT LOCATION: {self._region_name(hm['primary'])}")
            lines.append(f"• AREA AFFECTED: {hm['edited_percent']:.1f}% of the image")
            if hm['max_score'] > 0.5:
                lines.append(f"• SEVERITY: {hm['severity'].lower()} - significant manipulation present")
        else:
            lines.append(f"• HUMAN EDITING: Not detected (score: {h['score']:.2f})")
        
        if m['c2pa']:
            lines.append(f"• C2PA: Cryptographically signed - verifiable provenance")
        
        if m['camera_make']:
            lines.append(f"• CAMERA: {m['camera_make']} {m['camera_model']}")
        
        return '\n'.join(lines)
    
    # ============================================================
    # FILE & UPLOAD ANSWERS
    # ============================================================
    
    def _file_info(self, data, q=None):
        img = data['image']
        m = data['metadata']
        size_mb = img.image.size / (1024 * 1024)
        info = f"📄 Filename: {img.filename} ({size_mb:.1f} MB)"
        if m['width'] and m['height']:
            megapixels = (m['width'] * m['height']) / 1000000
            info += f", Resolution: {m['width']}x{m['height']} ({megapixels:.1f} MP)"
        return info
    
    def _upload_info(self, data, q=None):
        img = data['image']
        uploader = img.uploaded_by
        name = uploader.get_full_name() or uploader.username if uploader else "Guest"
        return f"Uploaded by {name} on {img.uploaded_at.strftime('%Y-%m-%d at %H:%M')}"
    
    # ============================================================
    # HEATMAP & SCORES ANSWERS
    # ============================================================
    
    def _heatmap_info(self, data, q=None):
        h = data['human_edit']
        hm = data['heatmap']
        if not h['is_edited']:
            return "The heatmap shows no significant hot spots - minimal to no editing detected. Most areas appear cool (blue/green)."
        
        region = self._region_name(hm['primary'])
        return f"The heatmap shows concentrated hot spots (red/orange areas) in the {region}. Maximum manipulation intensity: {hm['max_score']:.2f}. Used with overlay to visualize editing."
    
    def _scores(self, data, q=None):
        ai = data['ai']
        h = data['human_edit']
        hm = data['heatmap']
        return f"📊 SCORES SUMMARY:\n• AI Confidence: {ai['confidence']:.1f}%\n• Human Edit Score: {h['score']:.2f}\n• Max Edit Intensity: {hm['max_score']:.2f}\n• Average Edit Score: {hm['avg_score']:.2f}\n• Area Manipulated: {hm['edited_percent']:.1f}%"
    
    # ============================================================
    # RECOMMENDATION
    # ============================================================
    
    def _recommend(self, data, q=None):
        v = data['verdict']
        m = data['metadata']
        overall_conf = data.get('overall_confidence', 0)
        
        if v == "AUTHENTIC IMAGE":
            if m['c2pa']:
                return f"✅ HIGHLY RECOMMENDED: This image is authentic and C2PA-signed with verifiable provenance. Safe to use for any purpose."
            return f"✅ RECOMMENDED: This image appears authentic with {overall_conf:.1f}% confidence. Suitable for general use."
        if "AI Generated" in v:
            if m['ai_tool']:
                return f"⚠️ NOT RECOMMENDED for authentic content. This is AI-generated using {m['ai_tool']}. Use only if you understand it's synthetic."
            return "⚠️ NOT RECOMMENDED for authentic content. This image is AI-generated and does not represent real-world capture."
        if "Human Edited" in v:
            return "⚠️ USE WITH CAUTION: This image has been human-edited. Verify content independently before trusting."
        return "Review detailed analysis before using this image."
    
    # ============================================================
    # GENERAL FALLBACK
    # ============================================================
    
    def _general(self, data, q=None):
        v = data['verdict']
        h = data['human_edit']
        hm = data['heatmap']
        m = data['metadata']
        
        ai_tool = m.get('ai_tool', '')
        
        if h['is_edited']:
            if ai_tool:
                return f"This image is {v.lower()} - edited using {ai_tool} in the {self._region_name(hm['primary'])}. Ask 'Where exactly?' for details or 'Is it real?' for authenticity."
            return f"This image is {v.lower()}. Editing detected in the {self._region_name(hm['primary'])}. Ask 'Where exactly?' for details or 'What AI tool?' for more info."
        
        if m['c2pa']:
            return f"This image is {v.lower()} with C2PA signatures. No significant editing detected. Ask 'Is this AI?' or 'What camera was used?'"
        
        if ai_tool:
            return f"This image is {v.lower()} using {ai_tool}. No significant editing. Ask 'Is this AI?' for details."
        
        return f"This image is {v.lower()}. No significant editing detected. Ask 'Is this AI?', 'What camera was used?', or 'Should I trust it?'"


qa_system = ImageQASystem()